version: '2'
services:
  app:
    build: .
    image: mortonprod/boutique
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./server.js:/usr/src/app/server.js
      - ./client/build:/usr/src/app/client/build
      - ./productsImages:/usr/src/app/productsImages
    ports:
      - 4000:5000
    depends_on:
      - db
  db: 
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/data/db
    ports:
      - 27017